# Setting configuration file for cute
# Colors can be specified as:
# - Hex colors: '#RRGGBB' (e.g., '#0000FF' for blue)
# - ANSI color names: 'blue', 'red', 'green', 'yellow', 'cyan', 'magenta', 'white'
# - Combined styles: 'blue+bold', '#0000FF+bold', 'dim', etc.


[Theme]

[Interface]
background = "#212121"
border     = "#F25D94"
foreground = "#F0EDED"

[FileType]
directory  = "#0000FF+bold"
symlink    = "#00FFFF"
socket     = "#FFFF00"
pipe       = "#FF00FF"
device     = "#FFFF00+bold"
executable = "#00FF00"
regular    = "#F0EDED"

[Field]
group = "#00FFFF"
nlink = "#F0EDED"
size  = "#FFFF00"
time  = "#F0EDED"
user  = "#00FFFF"



[Permissions]
perm_exec  = "#FF5F00"
perm_read  = "#00FF00"
perm_write = "#FFFF00"
perm_none  = "#F0EDED"



[SearchBar]
search_bar_background     = "#212121"
search_bar_foreground     = "#F0EDED"
search_bar_border         = "#3B3B3B"
search_bar_placeholder    = "#888888"
search_bar_padding_top    = 0
search_bar_padding_bottom = 0
search_bar_padding_left   = 1
search_bar_padding_right  = 1

[CommandBar]
command_bar_background     = "#212121"
command_bar_foreground     = "#F0EDED"
command_bar_border         = "#3B3B3B"
command_bar_placeholder    = "#888888"
command_bar_padding_top    = 0
command_bar_padding_bottom = 0
command_bar_padding_left   = 1
command_bar_padding_right  = 1

[Selection]
selection_foreground = "#3B3B3B" # Selected item text color
selection_background = "#F0EDED" # Selected item background color

[FileList]
file_list_background     = ""
file_list_foreground     = ""
file_list_padding_top    = 0
file_list_padding_bottom = 1
file_list_padding_left   = 1
file_list_padding_right  = 1

[Preview]
preview_background     = ""
preview_foreground     = ""
preview_padding_top    = 0
preview_padding_bottom = 1
preview_padding_left   = 1
preview_padding_right  = 1

[Dialog]
dialog_background     = "#212121"
dialog_foreground     = "#F0EDED"
dialog_padding_top    = 1
dialog_padding_bottom = 1
dialog_padding_left   = 1
dialog_padding_right  = 1
dialog_border_color   = "#888888"

[Keybindings]
help_model="?"                 # open help modal
quit_app="ctrl+c"              # quit
resize_left="ctl+h"             # resize panel left
resize_right="ctl+l"           # resize panel right
up_a_parent_directory="ctrl+k"     # go up a parent directory
down_a_child_directory="ctrl+j"  # go down a child directory
previous_directory="ctrl+h"      # go to previous directory
next_directory="ctrl+l"         # go to next directory
home_directory="ctrl+a"          # go to home directory
root_directory="ctrl+e"           # go to root directory
open="enter"                   # opens file or directory

[Commands]
projects = "~/Projects"
docs_dir = "~/Docs"
music = "~/Music"
videos_dir = "~/Videos"
images = "~/Images"
dl = "~/Downloads"
desktop = "~/Desktop"
documents = "~/Documents"

